package trainpositions

import (
	"encoding/xml"
	"errors"
	"github.com/awiede/wmata-go-sdk/wmata"
	"github.com/kr/pretty"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"
)

// testClient is a mock implementation of wmata.HTTPClient interface used for testing purposes
type testClient struct{}

// ensure testClient implements wmata.HTTPClient interface
var _ wmata.HTTPClient = (*testClient)(nil)

// Do stubs out an httpClient.Do request
func (client *testClient) Do(req *http.Request) (*http.Response, error) {
	testResponses, exist := testData[req.URL.Path]

	if !exist {
		return nil, errors.New("no test data found")
	}

	for _, response := range testResponses {
		if response.rawQuery == req.URL.RawQuery {
			rr := httptest.NewRecorder()
			rr.WriteHeader(http.StatusOK)
			_, writeErr := rr.Write([]byte(response.response))

			return rr.Result(), writeErr
		}
	}

	return nil, errors.New("no data found")
}

type testResponseData struct {
	rawQuery             string
	responseType         wmata.ResponseType
	response             string
	expectedError        error
	unmarshalledResponse interface{}
}

var testData = map[string][]testResponseData{
	"/TrainPositions/TrainPositions": {
		{
			rawQuery:     "contentType=json",
			responseType: wmata.JSON,
			response:     `{"TrainPositions":[{"TrainId":"002","TrainNumber":"750","CarCount":6,"DirectionNum":2,"CircuitId":1618,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":7,"ServiceType":"NoPassengers"},{"TrainId":"004","TrainNumber":"701","CarCount":8,"DirectionNum":1,"CircuitId":109,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":9,"ServiceType":"NoPassengers"},{"TrainId":"015","TrainNumber":"506","CarCount":8,"DirectionNum":1,"CircuitId":2229,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":1,"ServiceType":"NoPassengers"},{"TrainId":"019","TrainNumber":"704","CarCount":8,"DirectionNum":1,"CircuitId":178,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":0,"ServiceType":"NoPassengers"},{"TrainId":"025","TrainNumber":"711","CarCount":6,"DirectionNum":2,"CircuitId":1610,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":0,"ServiceType":"NoPassengers"},{"TrainId":"027","TrainNumber":"703","CarCount":8,"DirectionNum":2,"CircuitId":1976,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":0,"ServiceType":"NoPassengers"},{"TrainId":"030","TrainNumber":"707","CarCount":0,"DirectionNum":1,"CircuitId":3424,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":37,"ServiceType":"NoPassengers"},{"TrainId":"041","TrainNumber":"606","CarCount":6,"DirectionNum":1,"CircuitId":3176,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":3,"ServiceType":"NoPassengers"},{"TrainId":"042","TrainNumber":"791","CarCount":8,"DirectionNum":2,"CircuitId":1904,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":37,"ServiceType":"NoPassengers"},{"TrainId":"044","TrainNumber":"710","CarCount":6,"DirectionNum":2,"CircuitId":1574,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":61,"ServiceType":"NoPassengers"},{"TrainId":"121","TrainNumber":"000","CarCount":8,"DirectionNum":1,"CircuitId":2581,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":363,"ServiceType":"Unknown"},{"TrainId":"129","TrainNumber":"000","CarCount":8,"DirectionNum":1,"CircuitId":2580,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":39377,"ServiceType":"Unknown"},{"TrainId":"170","TrainNumber":"000","CarCount":0,"DirectionNum":1,"CircuitId":1023,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":7394,"ServiceType":"Unknown"},{"TrainId":"178","TrainNumber":"706","CarCount":6,"DirectionNum":1,"CircuitId":2632,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":5,"ServiceType":"NoPassengers"},{"TrainId":"212","TrainNumber":"707","CarCount":8,"DirectionNum":2,"CircuitId":489,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":0,"ServiceType":"NoPassengers"},{"TrainId":"310","TrainNumber":"PM37","CarCount":0,"DirectionNum":1,"CircuitId":2976,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":1982,"ServiceType":"Unknown"},{"TrainId":"336","TrainNumber":"000","CarCount":0,"DirectionNum":2,"CircuitId":1012,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":1687,"ServiceType":"Unknown"},{"TrainId":"340","TrainNumber":"000","CarCount":0,"DirectionNum":2,"CircuitId":1010,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":3736,"ServiceType":"Unknown"},{"TrainId":"350","TrainNumber":"PM44","CarCount":0,"DirectionNum":1,"CircuitId":687,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":979,"ServiceType":"Unknown"},{"TrainId":"359","TrainNumber":"820","CarCount":6,"DirectionNum":1,"CircuitId":1130,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":106,"ServiceType":"NoPassengers"},{"TrainId":"360","TrainNumber":"000","CarCount":0,"DirectionNum":2,"CircuitId":3480,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":2205,"ServiceType":"Unknown"},{"TrainId":"361","TrainNumber":"GV01","CarCount":0,"DirectionNum":2,"CircuitId":2237,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":73,"ServiceType":"Unknown"},{"TrainId":"367","TrainNumber":"000","CarCount":0,"DirectionNum":2,"CircuitId":2957,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":123603,"ServiceType":"Unknown"},{"TrainId":"370","TrainNumber":"000","CarCount":0,"DirectionNum":2,"CircuitId":2798,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":123603,"ServiceType":"Unknown"},{"TrainId":"371","TrainNumber":"PM62","CarCount":0,"DirectionNum":1,"CircuitId":2119,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":109,"ServiceType":"Unknown"},{"TrainId":"376","TrainNumber":"000","CarCount":0,"DirectionNum":1,"CircuitId":2110,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":103,"ServiceType":"Unknown"},{"TrainId":"391","TrainNumber":"705","CarCount":6,"DirectionNum":1,"CircuitId":1041,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":0,"ServiceType":"NoPassengers"},{"TrainId":"478","TrainNumber":"701","CarCount":6,"DirectionNum":2,"CircuitId":1568,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":122,"ServiceType":"NoPassengers"},{"TrainId":"508","TrainNumber":"501","CarCount":8,"DirectionNum":2,"CircuitId":1899,"DestinationStationCode":null,"LineCode":null,"SecondsAtLocation":78,"ServiceType":"NoPassengers"},{"TrainId":"297","TrainNumber":"491","CarCount":6,"DirectionNum":1,"CircuitId":1135,"DestinationStationCode":"G05","LineCode":"BL","SecondsAtLocation":437,"ServiceType":"Normal"},{"TrainId":"465","TrainNumber":"403","CarCount":6,"DirectionNum":1,"CircuitId":2465,"DestinationStationCode":"G05","LineCode":"BL","SecondsAtLocation":0,"ServiceType":"Normal"},{"TrainId":"076","TrainNumber":"407","CarCount":8,"DirectionNum":2,"CircuitId":2706,"DestinationStationCode":"J03","LineCode":"BL","SecondsAtLocation":0,"ServiceType":"Normal"},{"TrainId":"505","TrainNumber":"492","CarCount":8,"DirectionNum":2,"CircuitId":1238,"DestinationStationCode":"J03","LineCode":"BL","SecondsAtLocation":5,"ServiceType":"Normal"},{"TrainId":"501","TrainNumber":"504","CarCount":2,"DirectionNum":1,"CircuitId":1895,"DestinationStationCode":"E10","LineCode":"GR","SecondsAtLocation":126,"ServiceType":"Normal"},{"TrainId":"506","TrainNumber":"591","CarCount":8,"DirectionNum":1,"CircuitId":1796,"DestinationStationCode":"E10","LineCode":"GR","SecondsAtLocation":58,"ServiceType":"Normal"},{"TrainId":"033","TrainNumber":"592","CarCount":8,"DirectionNum":2,"CircuitId":2338,"DestinationStationCode":"F11","LineCode":"GR","SecondsAtLocation":17,"ServiceType":"Normal"},{"TrainId":"500","TrainNumber":"508","CarCount":8,"DirectionNum":1,"CircuitId":2256,"DestinationStationCode":"F11","LineCode":"GR","SecondsAtLocation":267,"ServiceType":"Normal"},{"TrainId":"020","TrainNumber":"991","CarCount":6,"DirectionNum":1,"CircuitId":1475,"DestinationStationCode":"D13","LineCode":"OR","SecondsAtLocation":37,"ServiceType":"Normal"},{"TrainId":"050","TrainNumber":"992","CarCount":6,"DirectionNum":2,"CircuitId":1549,"DestinationStationCode":"K06","LineCode":"OR","SecondsAtLocation":29,"ServiceType":"Normal"},{"TrainId":"182","TrainNumber":"908","CarCount":8,"DirectionNum":2,"CircuitId":2826,"DestinationStationCode":"K06","LineCode":"OR","SecondsAtLocation":14,"ServiceType":"Normal"},{"TrainId":"047","TrainNumber":"192","CarCount":6,"DirectionNum":2,"CircuitId":662,"DestinationStationCode":"A15","LineCode":"RD","SecondsAtLocation":2,"ServiceType":"Normal"},{"TrainId":"219","TrainNumber":"104","CarCount":6,"DirectionNum":2,"CircuitId":244,"DestinationStationCode":"A15","LineCode":"RD","SecondsAtLocation":3,"ServiceType":"Normal"},{"TrainId":"346","TrainNumber":"105","CarCount":8,"DirectionNum":2,"CircuitId":294,"DestinationStationCode":"A15","LineCode":"RD","SecondsAtLocation":7,"ServiceType":"Normal"},{"TrainId":"118","TrainNumber":"191","CarCount":8,"DirectionNum":1,"CircuitId":203,"DestinationStationCode":"B11","LineCode":"RD","SecondsAtLocation":360,"ServiceType":"Normal"},{"TrainId":"208","TrainNumber":"102","CarCount":8,"DirectionNum":1,"CircuitId":652,"DestinationStationCode":"B11","LineCode":"RD","SecondsAtLocation":271,"ServiceType":"Normal"},{"TrainId":"496","TrainNumber":"202","CarCount":8,"DirectionNum":1,"CircuitId":591,"DestinationStationCode":"B11","LineCode":"RD","SecondsAtLocation":19,"ServiceType":"Normal"},{"TrainId":"492","TrainNumber":"601","CarCount":8,"DirectionNum":1,"CircuitId":2575,"DestinationStationCode":"G05","LineCode":"SV","SecondsAtLocation":146,"ServiceType":"Normal"},{"TrainId":"509","TrainNumber":"691","CarCount":8,"DirectionNum":1,"CircuitId":1437,"DestinationStationCode":"G05","LineCode":"SV","SecondsAtLocation":7,"ServiceType":"Normal"},{"TrainId":"014","TrainNumber":"692","CarCount":8,"DirectionNum":2,"CircuitId":2998,"DestinationStationCode":"N06","LineCode":"SV","SecondsAtLocation":18,"ServiceType":"Normal"},{"TrainId":"224","TrainNumber":"608","CarCount":2,"DirectionNum":2,"CircuitId":3334,"DestinationStationCode":"N06","LineCode":"SV","SecondsAtLocation":3,"ServiceType":"Normal"},{"TrainId":"136","TrainNumber":"392","CarCount":8,"DirectionNum":2,"CircuitId":1188,"DestinationStationCode":"C15","LineCode":"YL","SecondsAtLocation":10,"ServiceType":"Normal"}]}`,
			unmarshalledResponse: &GetLiveTrainPositionsResponse{
				Positions: []TrainPosition{
					{
						TrainID:                "002",
						TrainNumber:            "750",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1618,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      7,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "004",
						TrainNumber:            "701",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              109,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      9,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "015",
						TrainNumber:            "506",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2229,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "019",
						TrainNumber:            "704",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              178,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "025",
						TrainNumber:            "711",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1610,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "027",
						TrainNumber:            "703",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1976,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "030",
						TrainNumber:            "707",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              3424,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      37,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "041",
						TrainNumber:            "606",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              3176,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      3,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "042",
						TrainNumber:            "791",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1904,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      37,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "044",
						TrainNumber:            "710",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1574,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      61,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "121",
						TrainNumber:            "000",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2581,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      363,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "129",
						TrainNumber:            "000",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2580,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      39377,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "170",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              1023,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      7394,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "178",
						TrainNumber:            "706",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              2632,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      5,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "212",
						TrainNumber:            "707",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              489,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "310",
						TrainNumber:            "PM37",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2976,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1982,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "336",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              1012,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1687,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "340",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              1010,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      3736,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "350",
						TrainNumber:            "PM44",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              687,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      979,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "359",
						TrainNumber:            "820",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1130,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      106,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "360",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              3480,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      2205,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "361",
						TrainNumber:            "GV01",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2237,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      73,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "367",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2957,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      123603,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "370",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2798,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      123603,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "371",
						TrainNumber:            "PM62",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2119,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      109,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "376",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2110,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      103,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "391",
						TrainNumber:            "705",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1041,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "478",
						TrainNumber:            "701",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1568,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      122,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "508",
						TrainNumber:            "501",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1899,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      78,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "297",
						TrainNumber:            "491",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1135,
						DestinationStationCode: "G05",
						LineCode:               "BL",
						SecondsAtLocation:      437,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "465",
						TrainNumber:            "403",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              2465,
						DestinationStationCode: "G05",
						LineCode:               "BL",
						SecondsAtLocation:      0,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "076",
						TrainNumber:            "407",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2706,
						DestinationStationCode: "J03",
						LineCode:               "BL",
						SecondsAtLocation:      0,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "505",
						TrainNumber:            "492",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1238,
						DestinationStationCode: "J03",
						LineCode:               "BL",
						SecondsAtLocation:      5,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "501",
						TrainNumber:            "504",
						CarCount:               2,
						DirectionNumber:        1,
						CircuitID:              1895,
						DestinationStationCode: "E10",
						LineCode:               "GR",
						SecondsAtLocation:      126,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "506",
						TrainNumber:            "591",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              1796,
						DestinationStationCode: "E10",
						LineCode:               "GR",
						SecondsAtLocation:      58,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "033",
						TrainNumber:            "592",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2338,
						DestinationStationCode: "F11",
						LineCode:               "GR",
						SecondsAtLocation:      17,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "500",
						TrainNumber:            "508",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2256,
						DestinationStationCode: "F11",
						LineCode:               "GR",
						SecondsAtLocation:      267,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "020",
						TrainNumber:            "991",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1475,
						DestinationStationCode: "D13",
						LineCode:               "OR",
						SecondsAtLocation:      37,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "050",
						TrainNumber:            "992",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1549,
						DestinationStationCode: "K06",
						LineCode:               "OR",
						SecondsAtLocation:      29,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "182",
						TrainNumber:            "908",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2826,
						DestinationStationCode: "K06",
						LineCode:               "OR",
						SecondsAtLocation:      14,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "047",
						TrainNumber:            "192",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              662,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      2,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "219",
						TrainNumber:            "104",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              244,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      3,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "346",
						TrainNumber:            "105",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              294,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      7,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "118",
						TrainNumber:            "191",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              203,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      360,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "208",
						TrainNumber:            "102",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              652,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      271,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "496",
						TrainNumber:            "202",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              591,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      19,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "492",
						TrainNumber:            "601",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2575,
						DestinationStationCode: "G05",
						LineCode:               "SV",
						SecondsAtLocation:      146,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "509",
						TrainNumber:            "691",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              1437,
						DestinationStationCode: "G05",
						LineCode:               "SV",
						SecondsAtLocation:      7,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "014",
						TrainNumber:            "692",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2998,
						DestinationStationCode: "N06",
						LineCode:               "SV",
						SecondsAtLocation:      18,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "224",
						TrainNumber:            "608",
						CarCount:               2,
						DirectionNumber:        2,
						CircuitID:              3334,
						DestinationStationCode: "N06",
						LineCode:               "SV",
						SecondsAtLocation:      3,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "136",
						TrainNumber:            "392",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1188,
						DestinationStationCode: "C15",
						LineCode:               "YL",
						SecondsAtLocation:      10,
						ServiceType:            "Normal",
					},
				},
			},
		},
		{
			rawQuery:     "contentType=xml",
			responseType: wmata.XML,
			response:     `<TrainPositionResp xmlns="http://www.wmata.com" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><TrainPositions><TrainPosition><CarCount>6</CarCount><CircuitId>1618</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>10</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>002</TrainId><TrainNumber>750</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>110</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>0</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>004</TrainId><TrainNumber>701</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2229</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>3</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>015</TrainId><TrainNumber>506</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>179</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>0</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>019</TrainId><TrainNumber>704</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1610</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>2</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>025</TrainId><TrainNumber>711</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1976</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>2</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>027</TrainId><TrainNumber>703</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>3424</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>39</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>030</TrainId><TrainNumber>707</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>3176</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>6</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>041</TrainId><TrainNumber>606</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1904</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>39</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>042</TrainId><TrainNumber>791</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1574</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>63</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>044</TrainId><TrainNumber>710</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2581</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>366</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>121</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2580</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>39380</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>129</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>1023</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>7396</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>170</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>2633</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>0</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>178</TrainId><TrainNumber>706</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>488</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>1</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>212</TrainId><TrainNumber>707</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2976</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>1985</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>310</TrainId><TrainNumber>PM37</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>1012</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>1689</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>336</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>1010</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>3738</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>340</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>687</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>982</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>350</TrainId><TrainNumber>PM44</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1130</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>109</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>359</TrainId><TrainNumber>820</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>3480</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>2208</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>360</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2237</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>75</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>361</TrainId><TrainNumber>GV01</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2957</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>123606</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>367</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2798</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>123606</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>370</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2119</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>111</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>371</TrainId><TrainNumber>PM62</TrainNumber></TrainPosition><TrainPosition><CarCount>0</CarCount><CircuitId>2110</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>106</SecondsAtLocation><ServiceType>Unknown</ServiceType><TrainId>376</TrainId><TrainNumber>000</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1041</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>1</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>2</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>391</TrainId><TrainNumber>705</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1568</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>125</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>478</TrainId><TrainNumber>701</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1899</CircuitId><DestinationStationCode i:nil="true"/><DirectionNum>2</DirectionNum><LineCode i:nil="true"/><SecondsAtLocation>81</SecondsAtLocation><ServiceType>NoPassengers</ServiceType><TrainId>508</TrainId><TrainNumber>501</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1135</CircuitId><DestinationStationCode>G05</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>BL</LineCode><SecondsAtLocation>440</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>297</TrainId><TrainNumber>491</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>2467</CircuitId><DestinationStationCode>G05</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>BL</LineCode><SecondsAtLocation>1</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>465</TrainId><TrainNumber>403</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2706</CircuitId><DestinationStationCode>J03</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>BL</LineCode><SecondsAtLocation>2</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>076</TrainId><TrainNumber>407</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1238</CircuitId><DestinationStationCode>J03</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>BL</LineCode><SecondsAtLocation>8</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>505</TrainId><TrainNumber>492</TrainNumber></TrainPosition><TrainPosition><CarCount>2</CarCount><CircuitId>1895</CircuitId><DestinationStationCode>E10</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>GR</LineCode><SecondsAtLocation>129</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>501</TrainId><TrainNumber>504</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1796</CircuitId><DestinationStationCode>E10</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>GR</LineCode><SecondsAtLocation>61</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>506</TrainId><TrainNumber>591</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2338</CircuitId><DestinationStationCode>F11</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>GR</LineCode><SecondsAtLocation>19</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>033</TrainId><TrainNumber>592</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2256</CircuitId><DestinationStationCode>F11</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>GR</LineCode><SecondsAtLocation>270</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>500</TrainId><TrainNumber>508</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1475</CircuitId><DestinationStationCode>D13</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>OR</LineCode><SecondsAtLocation>39</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>020</TrainId><TrainNumber>991</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>1549</CircuitId><DestinationStationCode>K06</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>OR</LineCode><SecondsAtLocation>31</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>050</TrainId><TrainNumber>992</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2825</CircuitId><DestinationStationCode>K06</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>OR</LineCode><SecondsAtLocation>0</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>182</TrainId><TrainNumber>908</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>661</CircuitId><DestinationStationCode>A15</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>1</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>047</TrainId><TrainNumber>192</TrainNumber></TrainPosition><TrainPosition><CarCount>6</CarCount><CircuitId>244</CircuitId><DestinationStationCode>A15</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>6</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>219</TrainId><TrainNumber>104</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>294</CircuitId><DestinationStationCode>A15</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>10</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>346</TrainId><TrainNumber>105</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>203</CircuitId><DestinationStationCode>B11</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>363</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>118</TrainId><TrainNumber>191</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>652</CircuitId><DestinationStationCode>B11</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>274</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>208</TrainId><TrainNumber>102</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>591</CircuitId><DestinationStationCode>B11</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>RD</LineCode><SecondsAtLocation>22</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>496</TrainId><TrainNumber>202</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2575</CircuitId><DestinationStationCode>G05</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>SV</LineCode><SecondsAtLocation>149</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>492</TrainId><TrainNumber>601</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1437</CircuitId><DestinationStationCode>G05</DestinationStationCode><DirectionNum>1</DirectionNum><LineCode>SV</LineCode><SecondsAtLocation>10</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>509</TrainId><TrainNumber>691</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>2997</CircuitId><DestinationStationCode>N06</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>SV</LineCode><SecondsAtLocation>0</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>014</TrainId><TrainNumber>692</TrainNumber></TrainPosition><TrainPosition><CarCount>2</CarCount><CircuitId>3334</CircuitId><DestinationStationCode>N06</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>SV</LineCode><SecondsAtLocation>6</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>224</TrainId><TrainNumber>608</TrainNumber></TrainPosition><TrainPosition><CarCount>8</CarCount><CircuitId>1187</CircuitId><DestinationStationCode>C15</DestinationStationCode><DirectionNum>2</DirectionNum><LineCode>YL</LineCode><SecondsAtLocation>0</SecondsAtLocation><ServiceType>Normal</ServiceType><TrainId>136</TrainId><TrainNumber>392</TrainNumber></TrainPosition></TrainPositions></TrainPositionResp>`,
			unmarshalledResponse: &GetLiveTrainPositionsResponse{
				XMLName: xml.Name{
					Space: "http://www.wmata.com",
					Local: "TrainPositionResp",
				},
				Positions: []TrainPosition{
					{
						TrainID:                "002",
						TrainNumber:            "750",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1618,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      10,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "004",
						TrainNumber:            "701",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              110,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "015",
						TrainNumber:            "506",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2229,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      3,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "019",
						TrainNumber:            "704",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              179,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "025",
						TrainNumber:            "711",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1610,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      2,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "027",
						TrainNumber:            "703",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1976,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      2,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "030",
						TrainNumber:            "707",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              3424,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      39,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "041",
						TrainNumber:            "606",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              3176,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      6,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "042",
						TrainNumber:            "791",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1904,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      39,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "044",
						TrainNumber:            "710",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1574,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      63,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "121",
						TrainNumber:            "000",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2581,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      366,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "129",
						TrainNumber:            "000",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2580,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      39380,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "170",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              1023,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      7396,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "178",
						TrainNumber:            "706",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              2633,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      0,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "212",
						TrainNumber:            "707",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              488,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "310",
						TrainNumber:            "PM37",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2976,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1985,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "336",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              1012,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      1689,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "340",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              1010,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      3738,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "350",
						TrainNumber:            "PM44",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              687,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      982,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "359",
						TrainNumber:            "820",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1130,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      109,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "360",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              3480,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      2208,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "361",
						TrainNumber:            "GV01",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2237,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      75,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "367",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2957,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      123606,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "370",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        2,
						CircuitID:              2798,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      123606,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "371",
						TrainNumber:            "PM62",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2119,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      111,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "376",
						TrainNumber:            "000",
						CarCount:               0,
						DirectionNumber:        1,
						CircuitID:              2110,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      106,
						ServiceType:            "Unknown",
					},
					{
						TrainID:                "391",
						TrainNumber:            "705",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1041,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      2,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "478",
						TrainNumber:            "701",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1568,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      125,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "508",
						TrainNumber:            "501",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1899,
						DestinationStationCode: "",
						LineCode:               "",
						SecondsAtLocation:      81,
						ServiceType:            "NoPassengers",
					},
					{
						TrainID:                "297",
						TrainNumber:            "491",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1135,
						DestinationStationCode: "G05",
						LineCode:               "BL",
						SecondsAtLocation:      440,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "465",
						TrainNumber:            "403",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              2467,
						DestinationStationCode: "G05",
						LineCode:               "BL",
						SecondsAtLocation:      1,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "076",
						TrainNumber:            "407",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2706,
						DestinationStationCode: "J03",
						LineCode:               "BL",
						SecondsAtLocation:      2,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "505",
						TrainNumber:            "492",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1238,
						DestinationStationCode: "J03",
						LineCode:               "BL",
						SecondsAtLocation:      8,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "501",
						TrainNumber:            "504",
						CarCount:               2,
						DirectionNumber:        1,
						CircuitID:              1895,
						DestinationStationCode: "E10",
						LineCode:               "GR",
						SecondsAtLocation:      129,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "506",
						TrainNumber:            "591",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              1796,
						DestinationStationCode: "E10",
						LineCode:               "GR",
						SecondsAtLocation:      61,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "033",
						TrainNumber:            "592",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2338,
						DestinationStationCode: "F11",
						LineCode:               "GR",
						SecondsAtLocation:      19,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "500",
						TrainNumber:            "508",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2256,
						DestinationStationCode: "F11",
						LineCode:               "GR",
						SecondsAtLocation:      270,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "020",
						TrainNumber:            "991",
						CarCount:               6,
						DirectionNumber:        1,
						CircuitID:              1475,
						DestinationStationCode: "D13",
						LineCode:               "OR",
						SecondsAtLocation:      39,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "050",
						TrainNumber:            "992",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              1549,
						DestinationStationCode: "K06",
						LineCode:               "OR",
						SecondsAtLocation:      31,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "182",
						TrainNumber:            "908",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2825,
						DestinationStationCode: "K06",
						LineCode:               "OR",
						SecondsAtLocation:      0,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "047",
						TrainNumber:            "192",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              661,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      1,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "219",
						TrainNumber:            "104",
						CarCount:               6,
						DirectionNumber:        2,
						CircuitID:              244,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      6,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "346",
						TrainNumber:            "105",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              294,
						DestinationStationCode: "A15",
						LineCode:               "RD",
						SecondsAtLocation:      10,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "118",
						TrainNumber:            "191",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              203,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      363,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "208",
						TrainNumber:            "102",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              652,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      274,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "496",
						TrainNumber:            "202",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              591,
						DestinationStationCode: "B11",
						LineCode:               "RD",
						SecondsAtLocation:      22,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "492",
						TrainNumber:            "601",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              2575,
						DestinationStationCode: "G05",
						LineCode:               "SV",
						SecondsAtLocation:      149,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "509",
						TrainNumber:            "691",
						CarCount:               8,
						DirectionNumber:        1,
						CircuitID:              1437,
						DestinationStationCode: "G05",
						LineCode:               "SV",
						SecondsAtLocation:      10,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "014",
						TrainNumber:            "692",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              2997,
						DestinationStationCode: "N06",
						LineCode:               "SV",
						SecondsAtLocation:      0,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "224",
						TrainNumber:            "608",
						CarCount:               2,
						DirectionNumber:        2,
						CircuitID:              3334,
						DestinationStationCode: "N06",
						LineCode:               "SV",
						SecondsAtLocation:      6,
						ServiceType:            "Normal",
					},
					{
						TrainID:                "136",
						TrainNumber:            "392",
						CarCount:               8,
						DirectionNumber:        2,
						CircuitID:              1187,
						DestinationStationCode: "C15",
						LineCode:               "YL",
						SecondsAtLocation:      0,
						ServiceType:            "Normal",
					},
				},
			},
		},
	},
}

// setupTestService creates a service struct with a mock http client
func setupTestService(responseType wmata.ResponseType) *Service {
	wmataClient := wmata.Client{
		HTTPClient: &testClient{},
	}
	return NewService(&wmataClient, responseType)
}

func TestGetLiveTrainPositions(t *testing.T) {
	testRequests, exist := testData["/TrainPositions/TrainPositions"]

	if !exist {
		t.Errorf("no data found for GetLiveTrainPositions")
		return
	}

	for _, request := range testRequests {
		testService := setupTestService(request.responseType)
		response, responseErr := testService.GetLiveTrainPositions()

		if responseErr != nil {
			if request.expectedError == nil || responseErr.Error() != request.expectedError.Error() {
				t.Errorf("unexpected error: %s", responseErr)
			}
			continue
		}

		if !reflect.DeepEqual(response, request.unmarshalledResponse) {
			t.Error(pretty.Diff(response, request.unmarshalledResponse))
		}
	}
}
